### ISSUE TITLE
force_create and repository templates

### ISSUE THREAD

**Issue by affrae** [github/safe-settings#170]
Hi - can you go into a little more detail about how `force_create`, `template` and repository templates are meant to work?

**Comment by affrae** [comment]
@kleeadrian 👆

**Comment by decyjphr** [comment]
@affrae, `safe-settings` normally will not create a repo if there is a repo settings file but no corresponding repo. That behavior could be modified by having a setting called
`force_create:  true` in the repo-level settings file, and that would create the repo first and then apply the settings. This could be useful if the repo creation by members is not allowed and you want safe-settings to handle the repo creation.
When safe-settings creates a repo,  you can optionally specify that the repo be created from a template repo by passing a template repo name in 
`template:` config.

**Comment by affrae** [comment]
Makes sense now - thank you!!

**Comment by decyjphr** [comment]
Closing this issue based on feedback
