### ISSUE TITLE
The nop status check fails on pull requests with only 1 commit

### ISSUE THREAD

**Issue by joshjohanning** [github/safe-settings#185]
## Problem Description

@moensch discovered that pull requests with only 1 commit fail the `nop` status check. 

### What is actually happening

This just "hangs" forever:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/19912012/155636455-d5e83573-1641-4f41-ac24-fd59741e1c2b.png">

### What is the expected behavior

When you send another commit to this branch, then it succeeds:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/19912012/155636423-7269e906-8e62-441a-9d84-fc250e950df7.png">

### Error output, if available

```
status: 404
request: {
    method: "GET"
    url: "https://api.github.com/repos/joshjohanning-org-safe-settings/admin/compare/0000000000000000000000000000000000000000...5f7d787b1a886fd614a9a5b271a5c149a904750f"
    headers: {
      "accept": "application/vnd.github.v3+json",
      "user-agent": "probot/12.2.0 octokit-core.js/3.5.1 Node.js/14.19.0 (linux; x64)",
      "authorization": "token [REDACTED]"
    }
    request: {}
}
```

Not sure where in the code this is, but I think we should be doing something like: 

```
HEAD...5f7d787b1a886fd614a9a5b271a5c149a904750f
```

instead of 

```
0000000000000000000000000000000000000000...5f7d787b1a886fd614a9a5b271a5c149a904750f
```

### Are you using the hosted instance of probot/settings or running your own?

Running my own

### If running your own instance, are you using it with github.com or GitHub Enterprise?

github.com

**Comment by svg153** [comment]
Same error here... running on AKS cluster following the [deploy.md](https://github.com/github/safe-settings/blob/main-enterprise/docs/deploy.md) and the [deploy-k8s.yml](https://github.com/github/safe-settings/blob/main-enterprise/.github/workflows/deploy-k8s.yml)

log:
```json
    "response": {
        "url": "https://api.github.com/repos/<ORG>/admin/compare/0000000000000000000000000000000000000000...cd8525c7c1c483e0d11c2c986cbe5e48d3af5b8a",
        "status": 404,
        "headers": {"..."},
        "data": {
            "message": "Not Found",
            "documentation_url": "https://docs.github.com/rest/reference/repos#compare-two-commits"
        }
    },
    "request": {    
        "method": "GET",
        "url": "https://api.github.com/repos/<ORG>/admin/compare/0000000000000000000000000000000000000000...cd8525c7c1c483e0d11c2c986cbe5e48d3af5b8a",
        "headers": {
            "accept": "application/vnd.github.v3+json",
            "user-agent": "probot/12.2.0 octokit-core.js/3.5.1 Node.js/14.17.6 (linux; x64)",
            "authorization": "token [REDACTED]"
        },
        "request": {}
    },
    "event": {"..."},
    "stack": "HttpError: Not Found\n    at /opt/safe-settings/node_modules/@octokit/request/dist-node/index.js:86:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async sendRequestWithRetries (/opt/safe-settings/node_modules/@octokit/auth-app/dist-node/index.js:466:12)\n    at async Job.doExecute (/opt/safe-settings/node_modules/bottleneck/light.js:405:18)",
    "type": "Error",
    "msg": "Not Found"
```

cc: @gomete

**Comment by svg153** [comment]
It has happened again, but with a pull request that had more than one commit.

I've been looking, and I think it's related to these fixes in other projects:

- [Ensure files determiner works on PRs and new branches](https://github.com/microadam/drone-config-changeset-conditional/commit/40fd675ffca732c080b5c8558d946328966d30a7#)
- [Support scenario where check_suite.before is null](https://github.com/status-im/packages-check-bot/commit/5d3bbcfed0e9c7946a3040c9ec65ea2f1408cc53#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R153)
- [handle new branch pushed with commit](https://github.com/pholleran/toc-me/commit/dff2c35a16b19a5d3b209afe594e7ed24631c2bb#)
