### ISSUE TITLE
Members of teams are not synced

### ISSUE THREAD

**Issue by krsna-m** [github/safe-settings#251]
## Problem Description
- Add members to a team via `.github/settings.yml` 
- Add members manually to a team

### What is actually happening
- the members from `.github/settings.yml` are not auto added
- the manually added member is left alone

### What is the expected behavior
- the members from `.github/settings.yml` should be synced
- any members not in `.github/settings.yml` should be removed ie a full sync should happen

### Are you using the hosted instance of probot/settings or running your own?
hosted

**Comment by svg153** [comment]
Hello @kvmware 

As far as I know, with this application, you cannot manage the team members of an organization, this functionality is not implemented, therefore, it would not be a bug.

What you can do, is manage the default permissions that each team has for all the organization's repositories or for a specific one. Or give a specific permission to a specific user for all the repositories of the organization or for a specific one.

But, @decyjphr or @tspascoal can help you.
