### ISSUE TITLE
Safe Settings Validator check never stops

### ISSUE THREAD

**Issue by ghost** [github/safe-settings#270]
### What is actually happening
Safe Settings Validator check always present never stops or cancels ( Starting NOP ... )
### What is the expected behavior
to cancel at some point
### Error output, if available

```

```

## Context
On every pull request this safe settings validator check starts but never ends has been running : Starting NOP for Started 24d 23h 44m 47s ago, is it possible to disable this?
### Are you using the hosted instance of probot/settings or running your own?
Self-Hosted Instance
### If running your own instance, are you using it with github.com or GitHub Enterprise?
GitHub Enterprise 
#### Version of probot/settings
not sure must be around 1-2 month old
#### Version of GitHub Enterprise
3.5.4

**Comment by svg153** [comment]
Possibly related to #245. Could you confirm it?
A possible way to cancel it is to do what is commented [here](https://github.com/github/safe-settings/issues/217#issuecomment-1139554493)

**Comment by ghost** [comment]
@svg153 Thanks for the second link it seems that might be something that we can use.
But i think it might also be related to us having custom plugins and we might have removed/commented some code related to NOP. 
I mainly wanted to know if its possible to disable this check run in general to not appear at all.

**Comment by decyjphr** [comment]
Ok, so you don't want PR checks to be triggered in the first place? 
One way would be not to send the checks to the Github App. You could change the GitHub app configuration and uncheck the `Check run` and `Check suite` events. 
<img width="958" alt="image" src="https://user-images.githubusercontent.com/57544838/187957827-e57a82ab-7da3-42c2-86bd-99fb8b0627f2.png">

**Comment by ghost** [comment]
Will try to do that, thank you for the solutions both of you :)

**Comment by martinm82** [comment]
Would it be possible to report somehow all logs created by the validator to the pull request? We are as well facing the problem that the validator sometimes does not stop and we have no possibility to figure out what the real problem is. Probably by diving into the huge amount of the Probot logs would indicate the problem but for our users this is not possible. 

Any ideas?

**Comment by ghost** [comment]
If you have all the GitHub App Settings correct, the only case where this happened to me is when you introduce modifications or custom plugins, if the NOP related lines of code have an issue then it will get stuck, or also in case you make a mistake in the YML and define some value like instead of saying "push" in the permission for teams you wrote "write". But this is only my personal experience.
