### ISSUE TITLE
Repository settings not being applied on Baseline change

### ISSUE THREAD

**Issue by Michael-Burke** [github/safe-settings#285]
## Problem Description
Repository settings (.github/repos/*.yml) isn't overriding the baseline settings (.github/settings.yml)
### What is actually happening
I'm updating the base configuration in `.github/settings.yml`, getting it approved and merging into the default_branch. One this gets detected by the Github App, it enforces that baseline configuration across the designated repositories WITHOUT considering the override settings in the `repos` folder. The result is that specific teams I've configured in the override file are removed since they aren't present merely in the `.github/settings.yml`.

### What is the expected behavior
I would expect that when applying the default configuration, it would have followup step where it then applies the override settings from the `repos` folder/*.yml file. From first to last, a baseline configuration apply, followed by a SubOrg configuration override, followed by a Repo specific override.

### Error output, if available
No errors in the Github App logs or the Probot logs.

## Context
Using the probot application stood up in a kubernetes cluster in its own namespace. I deployed it using the helm chart provided and followed the instructions carefully.

### Are you using the hosted instance of probot/settings or running your own?
Running my own. Deployed using the deploy.md instructions for helm charts.

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com, no Enterprise.

#### Version of probot/settings
v12.2.5

#### Version of GitHub Enterprise
Using Github without Enterprise

**Comment by decyjphr** [comment]
Hi, @Michael-Burke Which version are you seeing this issue with? Would it be possible to check on version 2.x?

**Comment by Michael-Burke** [comment]
I will pull latest, update and then comment here. Thank you for the quick reply!

**Comment by Michael-Burke** [comment]
Hi @decyjphr,
I updated to 2.0.9. In testing, I'm not able to test my above due to the following error on PUSH events:

```
AggregateError: 
    TypeError: Cannot read property 'error' of undefined
        at /opt/safe-settings/lib/configManager.js:20:18
        at async ConfigManager.loadYaml (/opt/safe-settings/lib/configManager.js:19:24)
        at async syncSettings (/opt/safe-settings/index.js:70:29)
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)
```
I'm guessing I miss configured something in the values.yml when I deployed in helm? I also noticed when deploying with Helm that the values.yml will error `A valid appEnv.DEPLOYMENT_CONFIG_FILE is required!`. I worked around this by adding `DEPLOYMENT_CONFIG_FILE: deploymentConfig` but thought I would mention

**Comment by decyjphr** [comment]
Ah yes, if you are using Helm. Please make sure you pass the value of `DEPLOYMENT_CONFIG_FILE: "/app/deployment-config.yaml"` 

Sorry, I haven't had many customers use Helm, and I didn't have everything documented properly.

More details: The values.yml in the Helm chart has this value
```
deploymentConfig:
  restrictedRepos:
    exclude:
      - safe-settings
      - admin
      - .github
  configvalidators:
    - plugin: repository
      error: |
        `Repo name cannot start with 'test' `
      script:
        return !baseconfig.name.startsWith('stest')
    - plugin: collaborators
      error: |
        `Admin cannot be assigned to collaborators`
      script: |
        console.log(`baseConfig ${JSON.stringify(baseconfig)}`)
        return baseconfig.permission != 'admin'
  overridevalidators:
    - plugin: branches
      error: |
        `Branch protection required_approving_review_count cannot be overidden to a lower value`
      script: |
        console.log(`baseConfig ${JSON.stringify(baseconfig)}`)
        console.log(`overrideConfig ${JSON.stringify(overrideconfig)}`)
        if (baseconfig.protection.required_pull_request_reviews.required_approving_review_count && overrideconfig.protection.required_pull_request_reviews.required_approving_review_count ) {
          return overrideconfig.protection.required_pull_request_reviews.required_approving_review_count >= baseconfig.protection.required_pull_request_reviews.required_approving_review_count
        }
        return true
    - plugin: labels
      error: |
        Some error
      script: |
        return true
``` 

and you can override that if needed.

**Comment by Michael-Burke** [comment]
Using the value of `DEPLOYMENT_CONFIG_FILE: "/app/deployment-config.yaml"` resulted in a directory being created in the pod instead of a file. I got the error: 
```
AggregateError: 
    Error: EISDIR: illegal operation on a directory, read
```
I appreciate the reponse! Really excited to get this working for my organization. -- see below for edit

---
This was my mistake and a build error occurred -- Resolved. The error is currently:
```
AggregateError: 
    TypeError: Cannot read property 'error' of undefined
        at /opt/safe-settings/lib/configManager.js:20:18
        at async ConfigManager.loadYaml (/opt/safe-settings/lib/configManager.js:19:24)
        at async syncSettings (/opt/safe-settings/index.js:70:29)
        at async Promise.all (index 0)
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)
```

I believe this is because in `/lib/configManager.js` line 20 is `this.log.error` which I believe should similar to  `console.log` of `robot.log`. I'll open a separate issue on this later but mainly interested to find out why its catching that error

**Comment by Michael-Burke** [comment]
The original issue is solved in version 2.x.
