### ISSUE TITLE
Timeouts with lambda functions

### ISSUE THREAD

**Issue by nicacioliveira** [github/safe-settings#288]
## Problem Description and Context

In the organization where I work, we have more than 2k repositories and we have worries about this scenario because after I configured the lambda function with this application, I had a little problem with timeouts when we changed a single repository configuration and one push happens calling the lambda function.

The problem with timeouts happens when one patch in one repository make a change in the repository description. The default timeout is 3s, but after I changed to 6s, all pushes seems ok, but with this only little change we need 6s of timeout.

## Question

Are there any specific timeout recommendations for lambda functions (and high timing is to be expected) or is it a performance issue you worry about in the future?

**Comment by decyjphr** [comment]
Did you follow the instructions [here](https://github.com/github/safe-settings/blob/main-enterprise/docs/AWS-README.md)?   Or you can directly look at the link https://bobbyhadz.com/blog/aws-lambda-task-timed-out-after-seconds.

**Comment by decyjphr** [comment]
I'd go with the max. I have seen safe-settings take about 30 mins to converge the settings for all the repos if we are talking about 1000's of repos. Mostly it is because of `abuse` limits which will be triggered and API calls would be throttled by GitHub.

**Comment by nicacioliveira** [comment]
@decyjphr Hi, thank you for the answer, I made a deployment using containers and because of that, I didn't see the point with timeout maximum.

I will make this change.
