### ISSUE TITLE
[Question] Safe-settings cron with lambda via serverless

### ISSUE THREAD

**Issue by viks-confluent** [github/safe-settings#313]
I have my safe settings lambda up and running (via serverless) and verified everything works fine. I want to run these settings periodically via lambda setup. As this is a lambda function, node-cron does not make sense.

NOTE: I tried creating a Cloudwatch event to trigger lambda function. However that is triggering the Serverless handler webhook which is not actually running the settings bot code.

So what is the suggested approach in running the lambda periodically to reconfigure settings for all the repos in the organization ? Any documentation would be appreciated.

**Comment by viks-confluent** [comment]
@decyjphr  any suggestions on this ?

**Comment by decyjphr** [comment]
I am not knowledgeable in AWS lambda, but I believe you'd have to simulate a push happening for the settings.yml to trigger a full sync.  For that, you need the right headers and payload to send to safe-settings. 
The request itself would be like this:
```bash
curl -X POST --header @headers.txt --data @payload.json https://xxxxxxx.execute-api.us-east-1.amazonaws.com/api/github/webhooks
````
You'd have to create the `headers.txt` and `payload.json`. For that, in your org where `safe-settings` is installed, you can look at the `advanced` tab to see the payload and headers and use that to create the file. 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/57544838/196544127-b35f3bdb-8f83-4061-9503-59c59356702b.png">

I think for the payload, all you'd need would be something like this: 
```json
{
  "ref": "refs/heads/main",
  "repository": {
    "name": "admin",
    "full_name": "decyjphr-org/admin",
    "owner": {
      "name": "decyjphr-org",
      "login": "decyjphr-org",
      "type": "Organization"
    },
    "organization": "decyjphr-org"
  },
  "organization": {
    "login": "decyjphr-org"
  },
  "sender": {
    "login": "decyjphr",
    "type": "User"
  },
  "installation": {
    "id": 1094,
    "node_id": "MDIzOzdGFsbGF0aW9uMTA5NDgxODA="
  },
  "commits": [
    {
      "added": [ ],
      "removed": [  ],
      "modified": [ ".github/settings.yml"  ]
    }
  ],
  "head_commit": {
    "added": [  ],
    "removed": [  ],
    "modified": [ ".github/settings.yml" ]
  }
}
```

I have not tried this and don't have the bandwidth to do it right now, but if you are able to trigger the app using `curl`, you should be able to make it run on a schedule using an `AWS step function` and `CloudWatch event`.

**Comment by viks-confluent** [comment]
@decyjphr  I already tried to simulate the same way (curl) mentioned above and I see the lambda gets the information, however as mentioned in the description, this is only triggering the Serverless handler webhook.  It is not triggering the actual probot code.  See the attached screenshot:

<img width="1336" alt="Screen Shot 2022-10-18 at 2 23 40 PM" src="https://user-images.githubusercontent.com/100234924/196547619-5179623c-33c5-4538-bddd-e611c0098800.png">

**Comment by decyjphr** [comment]
Ok. Just to confirm the url has the "api/github/webhooks" path?

**Comment by viks-confluent** [comment]
Yes. The url does have the path `api/github/webhooks`

**Comment by viks-confluent** [comment]
For others, we used the following path:

- in the index.js,  we exported the syncInstallation method inside the method. 
```
  // Export syncInstallation from this closure so it can be called by the handler
  module.exports.syncInstallation = syncInstallation

```

---

In the lambda handler we call the exported method.

handler.js
```
const lib = require('./')
createLambdaFunction(lib.app, {
  probot: createProbot()
})

module.exports.poller = async function (event, context) {
  await lib.syncInstallation()
}
```

---
In the serverless, we create a separate function which calls the handler at a regular interval.

```
  cronHandler:
    handler: handler.poller
    memorySize: 256
    timeout: 900 # 15 mins (max)
    environment:
      NODE_ENV: production
      LOG_LEVEL: debug
    events:
      - schedule:
          rate: rate(30 minutes)
          enabled: true
          input: {}

```
