### ISSUE TITLE
compareDeep issue for Collaborator plugin return false when there are changes

### ISSUE THREAD

**Issue by ghost** [github/safe-settings#329]
## Problem Description
With clearly to different arrays the compareDeep for the case of Collaborator return a wrong value,
even weirder when i try it with my username it works with 2-3 different usernames it doesn't
We wanted to have Safe Settings trigger when there is Collaborator ( User ), addition or edit so we added
```
  //Repo Collaborator user added
  robot.on('member.added', async context => {
    const { payload } = context
    const { sender } = payload
    robot.log.debug('member.added payload from ', JSON.stringify(sender))
    if (sender.type === 'Bot') {
      robot.log.debug('Repository member.added by a Bot')
      return
    }
    robot.log.debug('Repository member.added by a Human')
    return syncSettings(false, context)
  })

  //Repo Collaborator user edited
  robot.on('member.edited', async context => {
    const { payload } = context
    const { sender } = payload
    robot.log.debug('member.edited payload from ', JSON.stringify(sender))
    if (sender.type === 'Bot') {
      robot.log.debug('Repository member.edited by a Bot')
      return
    }
    robot.log.debug('Repository member.edited by a Human')
    return syncSettings(false, context)
  })
```
At the end of index.js, and it triggers but doesn't work as expected here is my suborg yml section for Collaborator:
iksathrr -> is a SITEADMIN/Entepriseadmin/Orgadmin
```
collaborators:
  - username: iksathrr
    permission: admin
```
When we manually added a user as in the example bellow ( adding user named IKSAMUSE who is a normal user ) it should recognize it as a change/addition and proceed in the Diffable code further to remove the user that has been added but is not part of the suborg config, what what we see is different with **two different lists the method of compareDeep return false** on changes:

```
{
    "level": 20,
    "time": 1668281917846,
    "pid": 25,
    "hostname": "ea3d0e30617e",
    "name": "probot",
    "name": "probot",
    "name": "event",
    "id": "99c0c130-62c1-11ed-9303-90a7e828743d",
    "msg": "Results of comparing Collaborators diffable target 
[{\"username\":\"iksathrr\",\"pendinginvite\":false,\"permission\":\"admin\"},{\"username\":\"iksamuse\",\"pendinginvite\":false,\"permission\":\"push\"}] 
with source [{\"username\":\"iksathrr\",\"permission\":\"admin\"}] is {\n  \"additions\": [],
\n  \"modifications\": [],\n  \"hasChanges\": false\n}"
}
```

an other example where the outcome is correct but the output is wrong, when i manually add user iksafagr ( SITEADMIN), it will say there were changes but it will mistakenly say the modification was the original user ( IKSATHRR who is SITEADMIN ), it should be the other way around:
```
{
    "level": 20,
    "time": 1668343402065,
    "pid": 24,
    "hostname": "7872fc73b2d1",
    "name": "probot",
    "name": "probot",
    "name": "event",
    "id": "c1308770-6350-11ed-854f-d20b42ae12f9",
    "msg": "Results of comparing Collaborators diffable target [{\"username\":\"iksafagr\",\"pendinginvite\":false,\"permission\":\"admin\"},{\"username\":\"iksathrr\",\"pendinginvite\":false,\"permission\":\"admin\"}]
 with source [{\"username\":\"iksathrr\",\"permission\":\"admin\"}]
 is {\n  \"additions\": [],\n  \"modifications\": [\n    {\n      \"username\": \"iksathrr\"\n    }\n  ],\n  \"hasChanges\": true\n}"
}
```
I did some more tests there were cases where the compareDeep was right in the sense that it gave the right output,
on what got added manually, not sure what is affecting this, but i found one common point that the outcome of
whether the collaborator gets added edited or removed correctly gets messed up if a SITE ADMIN is involved in any way
as in when you trigger a suborg change by editing the suborg yml and the repo has a SITEADMIN added to it
when the app tries to instead put on USERB ( Normal USER ) , the app can't fix it something goes wrong, or when the right user is on the repo but you manually add a SITEADMIN to the repo, it will result in the siteadmin user not being removed
 or some form of mess up.

Worst example of this i have seen is if we have the yml just like i mentioned above 
suborg yml defines collaborator IKSATHRR ( SITE admin ) with ADMIN permission, you proceed to manually add to the repo
 the user IKSAMUSE (normal user) with WRITE access what the app does, is remove IKSATHRR and
change the IKSAMUSE permission to ADMIN, which is catastrophic result,
the user who is defined in the yml loses access, the person who you added manually changes permission
from write to admin.

### What is actually happening
compareDeep return false for changes while being given two clearly different arrays, thus the code doesn't proceed,
and in our case the manually added user/collaborator doesn't get removed from the repo
### What is the expected behavior
Return a list of additions or modifications and hasChanges be true, and remove the collaborator from the repo.
### Error output, if available

```

```

### Are you using the hosted instance of probot/settings or running your own?
Running our own

### If running your own instance, are you using it with github.com or GitHub Enterprise?
Github Enterprise Server 3.6
#### Version of probot/Safe-settings
2.0.17
#### Version of GitHub Enterprise
3.6

Hi @decyjphr could you please have a short look, sorry to tag you i just your name in the commits often 😄

**Comment by decyjphr** [comment]
@GranitFazliuRB This is working as written. When safe-settings compares the changes that needs to be applied with the state in GitHub, it sees there is no need to apply the changes because `iksathrr` is already an admin. 
I see your point that the extra  collaborator `iksafagr` who is also added in Github manually (outside of safe-settings) should be removed, but the current design allows for the extra collaborators who were added externally to remain. 
If you really want to remove `iksafagr` then you add them to the Collaborators but provide a null entry for permission.

```yaml
collaborators:
  - username: iksathrr
    permission: admin
  - username: iksafagr
    permission:
```

**Comment by ghost** [comment]
Hi @decyjphr, thanks for the explanation i guess that makes sense, also didn't know that giving null entry for permission removes them that's handy! I'll close the issue now.
