### ISSUE TITLE
Future/Roadmap of safe-settings

### ISSUE THREAD

**Issue by martinm82** [github/safe-settings#330]
Hi all,

We are currently investigating the best way to manage our GitHub organization and its underlying repositories (and not only). We started some time ago with Terraform and the GitHub provider (https://registry.terraform.io/providers/integrations/github/5.8.0). Since we want to provide users the best and easiest way of managing/configuring their repositories we continued looking for further alternatives and found this Probot app (kudos to the maintainers and authors for creating this great app. It's really a great app, easy to setup and use 💯)

What are the future plans of this app. Is the app mainly focusing on the repositories or are there plans as well to support managing organization/enterprise settings, app integrations, creating of apps, etc.?

I am asking because we are looking into managing everything (enterprise, organization, repositories) and for now we have several ways to solve this:

- Plain REST API using Typescript, Octokit and co.
- [Terraform GitHub Provider](https://registry.terraform.io/providers/integrations/github/) (a layer on top of the first one)
- Terragrunt on top of Terraform to improve UX and provide a Yaml based interface for users. This would require some additional effort to implement (especially the overriding feature that comes out of the box in safe-settings).
- [cdktf](https://github.com/hashicorp/terraform-cdk) which puts one more layer on top of Terraform but gives us more flexibility for missing features that we could implement in Typescript/Python/etc.
- safe-settings for repositories + one of the options above

Knowing a bit the direction in which this project will go in the (near) future would help us making a decision.

Looking forward for you feedback.

**Comment by martinm82** [comment]
Also, would it be possible to enable GitHub Discussions where we could discuss things to avoid polluting Issues? Not sure whether this project is still active since a month there were no new releases. Looking at the number of open pull requests it as well looks like it is dead. I hope I am totally wrong with this

**Comment by svg153** [comment]
The problem is that this repository is only maintained by @decyjphr and is not officially supported by GitHub, so it depends on the free time to maintain it. It's a shame that this tool is not given official coverage and its development is pushed by GitHub when I believe that the philosophy of the tool is the best way to manage organizations by code.

**Comment by martinm82** [comment]
Oh, I was under the impression (due to the organization) that it is officially developed by GitHub.

Yes, it would be really great to get more attention on it as it really has potential and in my opinion it should be made at some point a builtin feature in GitHub.

**Comment by martinm82** [comment]
I see that @decyjphr has enabled Discussions. Closing this in favour of https://github.com/github/safe-settings/discussions/335.
