### ISSUE TITLE
Settings applied from pull request 

### ISSUE THREAD

**Issue by martinm82** [github/safe-settings#339]
### What is actually happening
Given a pull request in the `admin` repository with org `settings.yml`, it is possible that settings get applied on the whole organization even though the changes where not yet merged to the main branch.

### What is the expected behavior
Changes from branches/pull requests should never ever be applied before merging to the default branch.

I am reporting this issue since this definitely happened on our side and caused a lot of problems. I was actually expecting that changes get only applied on repositories when the PR is merged to main. I suspect that this happened during a manual trigger of the `re-run` feature of the safe-settings validator.

### Are you using the hosted instance of probot/settings or running your own?
Self-hosted

### If running your own instance, are you using it with github.com or GitHub Enterprise?
GitHub.com

#### Version of probot/settings
2.0.17

**Comment by decyjphr** [comment]
@martinm82 Did this issue cause teams to be removed accidentally? 

I found a bug in the code at https://github.com/github/safe-settings/blob/5dd8e7987f6bf685a44ad857d0c0cc3092cd7002/lib/plugins/teams.js#L75

The intention was to get the url of the REST endpoint but instead, it was calling the endpoint itself.

```
        new NopCommand(this.constructor.name, this.repo, this.github.request(
          `DELETE ${teamRepoEndpoint}`,
          { team_id: existing.id, ...this.repo, org: this.repo.owner }
        ), 'DELETE Team')
```

should be

```
        new NopCommand(this.constructor.name, this.repo, this.github.request.endpoint(
          `DELETE ${teamRepoEndpoint}`,
          { team_id: existing.id, ...this.repo, org: this.repo.owner }
        ), 'DELETE Team')
```

If you could confirm that would be great. And I'll do more checking to see if this is at other places also.

**Comment by martinm82** [comment]
Yes, all teams got removed. I am not 100% sure, that it set the teams to the values of the  org settings of the PR but for sure all teams were removed. 
We were able to restore only partially the permissions because the audit log does not contain the exact permissions that got revoked. Only which teams got changed/removed.

**Comment by decyjphr** [comment]
@martinm82 release [2.0.18-rc.1 ](https://github.com/github/safe-settings/releases/tag/2.0.18-rc.1) has the fix. I am asking around to see if there is a way to find out the permissions of the deleted teams.

**Comment by martinm82** [comment]
@decyjphr what is the expected behaviour of safe-settings in the following case:

- teams and collaborators on repositories got manually assigned 
- introducing org settings which touch teams and collaborators to define some default permissions for specific groups (e.g. security)
- is it expected that safe-settings will remove all manually assigned teams/collaborators and replace them with what is defined in org/suborg/repo settings
- or will safe-settings keep existing (manually) teams/collaborators and extend with the ones defined in the settings?

This question actually applies as well to other settings like, branch protections for branches not tracked in the settings, merge attributes, etc.

I am asking because we would like to rollout safe-settings soon on our organisation but after the latest removal of all the permissions we probably will need to do it first on a test organization.

**Comment by decyjphr** [comment]
> I am asking around to see if there is a way to find out the permissions of the deleted teams.

@martinm82 I checked with others, and the best option to restore the team(s) is currently to look at the audit log at the time of the team creation to see what was set to. 
There is a customer feedback issue on being able to rebuild teams that were accidentally removed and I could add you to that. If so, let me know your company name.

**Comment by decyjphr** [comment]
> * teams and collaborators on repositories got manually assigned
> * introducing org settings which touch teams and collaborators to define some default permissions for specific groups (e.g. security)
> * is it expected that safe-settings will remove all manually assigned teams/collaborators and replace them with what is defined in org/suborg/repo settings
> * or will safe-settings keep existing (manually) teams/collaborators and extend with the ones defined in the settings?

Currently, when there are changes to teams, collaborators, or other configuration items, safe-settings will overwrite the existing items in GitHub. 

When safe-settings was initially written this was not an issue, but now we have `security-managers` which is a team that is automatically added to all the repos in the org, so I think there is a need to add a flag to indicate that the configuration should be additive and existing items in GH should be kept (basically skip the deletion process).

**Comment by martinm82** [comment]
> > I am asking around to see if there is a way to find out the permissions of the deleted teams.
> 
> @martinm82 I checked with others, and the best option to restore the team(s) is currently to look at the audit log at the time of the team creation to see what was set to. There is a customer feedback issue on being able to rebuild teams that were accidentally removed and I could add you to that. If so, let me know your company name.

Yes, that is what we as well thought. But unfortunately we don't have that much of audit history available anymore. Regarding the customer feedback issue: I guess it is the one created recently by a colleague of mine at TomTom.
