### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by miran-hadziomerovic** [github/safe-settings#363]
## Discussed in https://github.com/github/safe-settings/discussions/349

<div type='discussions-op-text'>

<sup>Originally posted by **miran-hadziomerovic** December  5, 2022</sup>
Hi,

I am trying to setup the app to use within my organization, but I am unsuccessful. No apparent erros in the code is what is my issue.

I am trying to deploy the built docker image to an Azure webapp using azure/webapps-deploy@v2 action.

Here are my pre-release and release yamls. Am I doing anything obviously wrong? If you need more information, please let me know what can I provide.

I've converted the files to txt from yml so they can be uploaded
[create-pre-release-for-qna.txt](https://github.com/github/safe-settings/files/10154742/create-pre-release-for-qna.txt)
[create-release-for-qna.txt](https://github.com/github/safe-settings/files/10154743/create-release-for-qna.txt)

Any help would be greatly appreciated!

Thank you in advance.</div>

**Comment by decyjphr** [comment]
In your Azure portal, when you look at the configuration of the App, do you see `Application Settings`? You should at a minimum see things like 
APP_ID
LOG_LEVEL
PRIVATE_KEY
WEBHOOK_SECRET

Besides this, if you want to use a `deployment config`, you'd have to set the `DEPLOYMENT_CONFIG_FILE` value to the shared filesystem: you'd have to create a Azure File storge and mount the file and enter the path here.

I've never done this  but I know of one team that is running on App Service.
