### ISSUE TITLE
Check not being submitted back to PR

### ISSUE THREAD

**Issue by aJanuary** [github/safe-settings#380]
## Problem Description
I have a PR in the admin repo. I see the log line saying it is triggering the check, but then the AWS lambda immediately stops.

```
2023-01-17T10:13:50.260+00:00 DEBUG (probot): Pull_request opened !
2023-01-17T10:13:50.260+00:00 DEBUG (probot): Is Admin repo event true
2023-01-17T10:13:50.260+00:00 DEBUG (probot): Check suite was requested! for [object Object] 7 c3689df36907689081369ac43f6b2410365fb80f chore/babbott@newRepo-delphi-legacy
2023-01-17T10:13:50.299+00:00 END RequestId: 2710fffa-5143-40cd-b149-e4e7e7f0d43c
```

### What is actually happening
The code stops running shortly after saying the check suite was requested, with no extra logging. No check is appearing on the pull-request.

### What is the expected behavior
A check is added to the pull-request.

## Context
A PR is made in the admin repo.

### Are you using the hosted instance of probot/settings or running your own?
Running my own as a lambda in AWS.

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com

#### Version of probot/settings
2.0.20-alpha.4 (commit 15518fe7f14facf82138844948ac6ad20330ecfb)

**Comment by anderssonjohan** [comment]
Have you tried to run the app locally and debug the issue? I had something similar but for a change to a repository and the app died when it tried to send a request with an invalid body to the GitHub API. 

If this is something similar, please comment on which API call it is that fails and where. It would be most helpful to add further debug logging to avoid a similar situation in the future. It can be a bit frustrating to go into local debug mode to get the detail, but I couldn't come up with a better option when I was in this situation.

Btw, is it only one particular PR to the admin repo or all? If only one, can you try to make the simplest possible PR and see if that gives you some other output?
