### ISSUE TITLE
Support for environments

### ISSUE THREAD

**Issue by martinm82** [github/safe-settings#381]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
Yes, available under `Repository Settings` -> `Environment`

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
Yes, https://docs.github.com/en/rest/deployments/environments?apiVersion=2022-11-28

## New Feature

Similar to branch protection rules it would be great to configure deployment protection rules, deployment branches, secrets and variables

**Comment by svg153** [comment]
@martinm82 Might be duplicated with this one https://github.com/github/safe-settings/issues/291?

**Comment by martinm82** [comment]
@svg153 yeah, this is indeed a duplicate. I haven't taken the time to search first in the issues. My bad.

**Comment by martinm82** [comment]
@svg153 yeah, this is indeed a duplicate. I haven't taken the time to search first in the issues. My bad.

**Comment by anderssonjohan** [comment]
@martinm82 Just out of curiosity, can you elaborate a bit on the secrets part?

The only thing I can come up with is to be able to define what repos to add to an org-level secret, but that's something different than environments. The secret value itself is still managed manually, I'm only referring to the repo access list to an org-level secret. 
For non-secret variables, I totally see the value in having them defined once per environment (using safe-settings policy files) and then used in multiple repos via suborg configs, etc.

**Comment by svg153** [comment]
Hello, I think that the secrets part could be removed from the scope... Just having the base would be enough for now. Something like this: https://github.com/repository-settings/app/pull/671
PS: this issue is closed because it is duplicated with #291. We could open it again to do the secrets in this issue and have the base in the other.
