### ISSUE TITLE
Deployment-settings.yml file not being recognized

### ISSUE THREAD

**Issue by JDunnUKG** [github/safe-settings#508]
## Problem Description
In the section on Runtime Settings, the following is written:
The runtime settings are configured in deployment-settings.yml that is in the directory from where the GitHub app is running.

In the section on Pull Requests, the following is written:
The checks will fail if org-level branch protections are overridden at the repo or suborg level with a lesser number of required approvers.  This second statement mentions nothing about the deployment-settings.yml file.

In any event, I have tried running safe-settings with the deployment-settings.yml file in both the admin directory and in the same directory where I am executing the docker-compose command. 

In deployment-settings.yml, if a repo-level .yml file tries to lower the number of required approvers to less than what is set at the org-level, an error should be thrown.

### What is actually happening
None of the settings in deployment-settings.yml are being recognized.  The safe-settings check is passing.

### What is the expected behavior
An error should be thrown.  I would expect the safe-settings check to fail and prevent the PR from being merged.

### Error output, if available
No error output.   Safe-settings check passes.  No evidence that deployment-settings.yml is being recognized at all

```

```

**Comment by decyjphr** [comment]
@JDunnUKG Does your deployment settings file look similar to [this](https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/sample-deployment-settings.yml)?

**Comment by JDunnUKG** [comment]
The problem was not in the deployment-settings.yml file itself, but that the Docker container running safe-settings could not see it. We resolved this issue by adding a line to the Dockerfile to copy deployment-settings.yml into the container, and setting the DEPLOYMENT_CONFIG_FILE environment variable in the .env file to the location of where the deployment-settings.yml file was copied.
