### ISSUE TITLE
No Autolinks changes made if length of filteredEntries and existingRecords is equal

### ISSUE THREAD

**Issue by stevoland** [github/safe-settings#521]
## Problem Description

See failing unit test https://github.com/github/safe-settings/pull/520. If the length of the existing records is the same as the configuration, no changes are made.

### What is actually happening

No changes made

### What is the expected behavior

Autolinks should be created/deleted

### Error output, if available

Add `console.log(compare)` at https://github.com/github/safe-settings/blob/f0466d7776480db6921eeaa6e8ed1935f7d70524/lib/plugins/diffable.js#L79:

```
  console.log
    { additions: [], modifications: [], hasChanges: 0 }

      at log (lib/plugins/diffable.js:80:37)
```

**Comment by decyjphr** [comment]
Hi @stevoland the code in `decyjphr/repo-rules` branch should fix it. There are code changes that fixed a few things in the comparison code and all the tests were passing.  I'll confirm specifically if this is working.

**Comment by stevoland** [comment]
@decyjphr thanks I'll have a look

**Comment by stevoland** [comment]
```
$ git fetch upstream
$ git checkout decyjphr/repo-rules
$ git log -1
commit 2dd05c50509ad6c3d6b1317178b7d36ec4511b05 (HEAD -> decyjphr/repo-rules, upstream/decyjphr/repo-rules)
Author: Yadhav Jayaraman <57544838+decyjphr@users.noreply.github.com>
Date:   Sun Aug 20 16:27:28 2023 -0400

    repo level rulesets and better PR validation message
$ npm i
$ npm run test:unit
...
Test Suites: 7 failed, 5 passed, 12 total
Tests:       21 failed, 46 passed, 67 total
```

My test also still fails I'm afraid.
