### ISSUE TITLE
Addition of Merge Settings Message being set to Default to Pull Request Title and Description

### ISSUE THREAD

**Issue by amartyaroy** [github/safe-settings#530]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/
https://github.com/orgs/community/discussions/30439

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).
https://docs.github.com/en/enterprise-server@3.8/rest/repos/repos#update-a-repository

* If the functionality is not yet available in the API, it would be helpful if you
  contacted support (https://support.github.com/) or posted in the Community Forum (https://github.community/). Please
  include a link to the forum post if you create one or a copy of the response from support.

## New Feature

Please describe the desired new functionality:
I am trying to use this feature on repo level squash merge settings message to be set default to PR Title and Description. As the above UI suggest that its possible and the api is also available. So, i am wondering can i use this in the safe-settings also or not.I want to update this merge settings for all the repos in an org using the safe-settings.Currently I tried to add this parameter in admin repo
settings.yml    `squash_merge_commit_message: PR_BODY` but it returned me 500 error. 

So is it possible to provide a support for this too

**Comment by decyjphr** [comment]
Yes, you should be able to set this as it is allowed in the payload as per the documentation. 

I was able to test it.

The following are valid combinations for the squash commit title and message: PR_TITLE and PR_BODY, PR_TITLE and BLANK, PR_TITLE and COMMIT_MESSAGES, COMMIT_OR_PR_TITLE and COMMIT_MESSAGES.

**Comment by amartyaroy** [comment]
Hi @decyjphr 
Thanks for the support. It worked as expected.
