### ISSUE TITLE
Starting NOP endless initiating

### ISSUE THREAD

**Issue by darliiin** [github/safe-settings#555]
## Problem Description
no change or endless processing

### What is actually happening
I'm making changes to .github/settings.yaml
![Screenshot_20231116_104410](https://github.com/github/safe-settings/assets/117597862/880af7ce-4dc7-4a34-9eeb-cd6bdf4a61e3)

and I get these results:
1) either no changes
![Screenshot_20231116_103812](https://github.com/github/safe-settings/assets/117597862/cace580d-493e-440f-adc8-0a9048e0b7d5)
 not displayed

2)  or endless processing of changes
![Screenshot_20231116_103850](https://github.com/github/safe-settings/assets/117597862/e125da45-f78c-441d-853f-48d03a35d59c)

### What is the expected behavior
expected behavior: changelog
![Screenshot_20231116_132506](https://github.com/github/safe-settings/assets/117597862/797434bb-b8dc-40bc-b84b-1190bacab999)

### Error output, if available
no errors are shown in the logs
```

```

### Are you using the hosted instance of probot/settings or running your own?
use our own

### If running your own instance, are you using it with github.com or GitHub Enterprise?
using it with github.com

**Comment by bheemvennapureddy** [comment]
What does your .env looks like for the probot app ?

**Comment by svg153** [comment]
Most of the time this can be related to GitHub safe-settings app permissions. In any case, the log of the safe-settings application would be good to see what could have failed. You can set the log level to trace to get more information.
