### ISSUE TITLE
Cannot it run in from Docker but works on commad line

### ISSUE THREAD

**Issue by agustincelentano** [github/safe-settings#608]
Hi,

I am using this successfully by running the node command (I configured all as said) 

`npm start`

When building the docker image and running it says it's listening to localhost:3000 but it does not receive anything from smee.io webhook. I did not touch any template standard provided in the repository for the docker-compose or dockerfile files

From docker 
![image](https://github.com/github/safe-settings/assets/12614595/72b70e03-f4ac-440c-9c30-d1635ada12ad)

From command line
![image](https://github.com/github/safe-settings/assets/12614595/5f3fac62-9aa8-4938-9348-c73f50e492b8)

You can see that the last one receives the responses

What am I doing wrong here?

**Comment by svg153** [comment]
Hi.

I think it works as expected according to these two lines... smee client is only for development:
- `smee-client` dep in in [devDependencies in package.json](https://github.com/github/safe-settings/blob/90ae0ae4f686dc584495b0aa9caa4061db8970e6/package.json#L34): https://github.com/github/safe-settings/blob/90ae0ae4f686dc584495b0aa9caa4061db8970e6/package.json#L52
- In the Dockerfile, the NODE_ENV is set to production: https://github.com/github/safe-settings/blob/90ae0ae4f686dc584495b0aa9caa4061db8970e6/Dockerfile#L3

Solutions:
- Try to change the NODE_EMV in Dockerfile
- Use ngrok in your local machine to connect with safe-settings in Docker. See my testing org: https://github.com/svg153-org/admin/blob/main/apps/safe-settings-local/README.md#start

**Comment by agustincelentano** [comment]
It worked changed to use the devDepedencies when running docker locally. Thanks!
